services:
  qemu:
    image: qemux/qemu
    container_name: qemu
    environment:
      BOOT: "alma"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
      - ./nixos.iso:/boot.iso
    restart: always
    stop_grace_period: 2m
