#! /nix/store/cfqbabpc7xwg8akbcchqbq3cai6qq2vs-bash-5.2p37/bin/bash

export PATH=/nix/store/rry6qingvsrqmc7ll7jgaqpybcbdgf5v-coreutils-9.7/bin${PATH:+:}$PATH

set -e

# Create an empty ext4 filesystem image. A filesystem image does not
# contain a partition table but just a filesystem.
createEmptyFilesystemImage() {
  local name=$1
  local size=$2
  local temp=$(mktemp)
  /nix/store/xwknjyv9w7i1l2kzhrxfbf9mf8kkwl16-qemu-host-cpu-only-9.2.4/bin/qemu-img create -f raw "$temp" "$size"
  /nix/store/v0hf0465c5pr21hvvc034akr6f9qg8f6-e2fsprogs-1.47.2-bin/bin/mkfs.ext4 -L nixos "$temp"
  /nix/store/xwknjyv9w7i1l2kzhrxfbf9mf8kkwl16-qemu-host-cpu-only-9.2.4/bin/qemu-img convert -f raw -O qcow2 "$temp" "$name"
  rm "$temp"
}

NIX_DISK_IMAGE=$(readlink -f "${NIX_DISK_IMAGE:-./nixos.qcow2}") || test -z "$NIX_DISK_IMAGE"

if test -n "$NIX_DISK_IMAGE" && ! test -e "$NIX_DISK_IMAGE"; then
    echo "Disk image do not exist, creating the virtualisation disk image..."

    createEmptyFilesystemImage "$NIX_DISK_IMAGE" "8192M"

    echo "Virtualisation disk image created."
fi

# Create a directory for storing temporary data of the running VM.
if [ -z "$TMPDIR" ] || [ -z "$USE_TMPDIR" ]; then
    TMPDIR=$(mktemp -d nix-vm.XXXXXXXXXX --tmpdir)
fi



# Create a directory for exchanging data with the VM.
mkdir -p "$TMPDIR/xchg"







cd "$TMPDIR"



# Start QEMU.
exec /nix/store/xwknjyv9w7i1l2kzhrxfbf9mf8kkwl16-qemu-host-cpu-only-9.2.4/bin/qemu-system-x86_64 -machine accel=kvm:tcg -cpu max \
    -name nixos \
    -m 2048 \
    -smp 2 \
    -device virtio-rng-pci \
    -net nic,netdev=user.0,model=virtio -netdev user,id=user.0,"$QEMU_NET_OPTS" \
    -virtfs local,path=/nix/store,security_model=none,mount_tag=nix-store \
    -virtfs local,path="${SHARED_DIR:-$TMPDIR/xchg}",security_model=none,mount_tag=shared \
    -virtfs local,path="$TMPDIR"/xchg,security_model=none,mount_tag=xchg \
    -drive cache=writeback,file="$NIX_DISK_IMAGE",id=drive1,if=none,index=1,werror=report -device virtio-blk-pci,bootindex=1,drive=drive1,serial=root \
    -device virtio-keyboard \
    -usb \
    -device usb-tablet,bus=usb-bus.0 \
    -kernel ${NIXPKGS_QEMU_KERNEL_nixos:-/nix/store/9rb9g37hvj51qk4v9fj6by67y0d9l2b2-nixos-system-nixos-25.05.20250910.8cd5ce8/kernel} \
    -initrd /nix/store/yww1qrkwglpydpryhcxwwvvbi28gq451-initrd-linux-6.12.46/initrd \
    -append "$(cat /nix/store/9rb9g37hvj51qk4v9fj6by67y0d9l2b2-nixos-system-nixos-25.05.20250910.8cd5ce8/kernel-params) init=/nix/store/9rb9g37hvj51qk4v9fj6by67y0d9l2b2-nixos-system-nixos-25.05.20250910.8cd5ce8/init regInfo=/nix/store/bsnx21kpnmsglmbcn5989r4lxy0l4r48-closure-info/registration console=ttyS0,115200n8 console=tty0 $QEMU_KERNEL_PARAMS" \
    $QEMU_OPTS \
    "$@"
